// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	pb "github.com/v-starostin/go-metrics/internal/pb"
)

// GoMetricsServer is an autogenerated mock type for the GoMetricsServer type
type GoMetricsServer struct {
	mock.Mock
}

// PostMetrics provides a mock function with given fields: _a0, _a1
func (_m *GoMetricsServer) PostMetrics(_a0 context.Context, _a1 *pb.PostMetricsRequest) (*pb.PostMetricsResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PostMetrics")
	}

	var r0 *pb.PostMetricsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.PostMetricsRequest) (*pb.PostMetricsResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.PostMetricsRequest) *pb.PostMetricsResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.PostMetricsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.PostMetricsRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mustEmbedUnimplementedGoMetricsServer provides a mock function with given fields:
func (_m *GoMetricsServer) mustEmbedUnimplementedGoMetricsServer() {
	_m.Called()
}

// NewGoMetricsServer creates a new instance of GoMetricsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoMetricsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoMetricsServer {
	mock := &GoMetricsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
