// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	pb "github.com/v-starostin/go-metrics/internal/pb"
)

// GoMetricsClient is an autogenerated mock type for the GoMetricsClient type
type GoMetricsClient struct {
	mock.Mock
}

// PostMetrics provides a mock function with given fields: ctx, in, opts
func (_m *GoMetricsClient) PostMetrics(ctx context.Context, in *pb.PostMetricsRequest, opts ...grpc.CallOption) (*pb.PostMetricsResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PostMetrics")
	}

	var r0 *pb.PostMetricsResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *pb.PostMetricsRequest, ...grpc.CallOption) (*pb.PostMetricsResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *pb.PostMetricsRequest, ...grpc.CallOption) *pb.PostMetricsResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pb.PostMetricsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *pb.PostMetricsRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewGoMetricsClient creates a new instance of GoMetricsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGoMetricsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *GoMetricsClient {
	mock := &GoMetricsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
