// Code generated by mockery v2.38.0. DO NOT EDIT.

package mock

import (
	mock "github.com/stretchr/testify/mock"
	model "github.com/v-starostin/go-metrics/internal/model"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Load provides a mock function with given fields: mtype, mname
func (_m *Repository) Load(mtype string, mname string) (*model.Metric, error) {
	ret := _m.Called(mtype, mname)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *model.Metric
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.Metric, error)); ok {
		return rf(mtype, mname)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.Metric); ok {
		r0 = rf(mtype, mname)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Metric)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(mtype, mname)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadAll provides a mock function with given fields:
func (_m *Repository) LoadAll() (model.Data, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for LoadAll")
	}

	var r0 model.Data
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.Data, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.Data); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(model.Data)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreFromFile provides a mock function with given fields:
func (_m *Repository) RestoreFromFile() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for RestoreFromFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields: m
func (_m *Repository) Store(m model.Metric) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(model.Metric) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreMetrics provides a mock function with given fields: m
func (_m *Repository) StoreMetrics(m []model.Metric) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for StoreMetrics")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]model.Metric) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WriteToFile provides a mock function with given fields:
func (_m *Repository) WriteToFile() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for WriteToFile")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
