// Code generated by mockery v2.43.2. DO NOT EDIT.

package mock

import mock "github.com/stretchr/testify/mock"

// UnsafeGoMetricsServer is an autogenerated mock type for the UnsafeGoMetricsServer type
type UnsafeGoMetricsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedGoMetricsServer provides a mock function with given fields:
func (_m *UnsafeGoMetricsServer) mustEmbedUnimplementedGoMetricsServer() {
	_m.Called()
}

// NewUnsafeGoMetricsServer creates a new instance of UnsafeGoMetricsServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUnsafeGoMetricsServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UnsafeGoMetricsServer {
	mock := &UnsafeGoMetricsServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
